### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by adrai** [dot-base/vue-i18next#5]
Hi @dlw93 @friedow are you aware of this? https://github.com/panter/vue-i18next/issues/123#issuecomment-873463996
Would you be open to this idea?

**Comment by friedow** [comment]
Hey @adrai :)! 

I've just checked that with our team and we would love to maintain the vue-i18next library and in that effort upgrade it to vue 3. I've added this to our roadmap and this library will get an upgrade as soon as we upgrade our own frontend to vue 3. Since this is not scheduled yet, I can only offer PR reviews if you are willing to implement that yourself.

I'll update this issue as soon as there is any concrete scheduling for this on our side.

**Comment by adrai** [comment]
Unfortunately, I'm not a TypeScript user, but this file is probably a good start: https://github.com/i18next/i18next-http-backend/blob/master/example/vue/src/vue-i18next.js

btw: if you like we can also create a new repository under the i18next namespace and I'll give you admin access: i.e. https://github.com/i18next/vue-i18next

Since I'm also a maintainer of i18next, let me know if you need some help regarding i18next functionality...
PS. Gruss aus der Schweiz ;-)

**Comment by kpturner** [comment]
Not sure if this is going ahead or not.  The README example doesn't use Vue 3 syntax to create the Vue app but is that just because it is all in its infancy?

**Comment by adrai** [comment]
> Not sure if this is going ahead or not. The README example doesn't use Vue 3 syntax to create the Vue app but is that just because it is all in its infancy?

@kpturner the official migration to Vue 3 has not yet started (I think so).
So currently check out this: https://github.com/i18next/i18next-http-backend/blob/master/example/vue/src/vue-i18next.js

**Comment by friedow** [comment]
:exclamation: This repository has been migrated into the official i18next organization: https://github.com/i18next/vue-i18next. This repository is deprecated.
